model: contextual_rnn
train_data: data/train/metadata.csv
dev_data: data/dev/metadata.csv
gpu: 0
num_epochs: 100
batch_size: 8
glove_path: data/glove/glove.6B.300d.txt
glove_dim: 300
lr: 0.001
glove_train: True
dropout: 0.5
